// react/js/components/Files.js
var React = require("react");

var File = require("./File.js");
var open = require("./file-openers/ServerSideOpener");

var Files = React.createClass({
    openFiles: function () {
        open(this.props.files);
    },

    render: function() {
        return <table className="table table-striped">
            <tbody>
                <tr>
                    <th>
                        Showing {this.props.files.length} matching files

                        <a onClick={this.openFiles} className="btn btn-primary pull-right">
                            Open files
                        </a>
                    </th>
                </tr>

                {this.props.files.map(function (file) {
                    return <tr key={file.hash}><td><File file={file} /></td></tr>;
                })}
            </tbody>
        </table>;
    }
});

module.exports = Files;

// src/client/app/components/files.component.ts
import {Component, OnInit, Injectable, Inject} from "@angular/core";
import {Observable} from "rxjs/Rx";

import {File} from "./../models/file";
import {Tag} from "./../models/tag";
import {FileQuery} from "./../models/filequery";
import {LaputinService} from "./../services/laputinservice";

@Component({
    template: `
        <file-search (update)="filterFiles($event)"></file-search>        
    
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>
                        Showing {{files.length}} matching files

                        <a class="btn btn-primary pull-right" (click)="openFiles()">
                            Open files
                        </a>
                    </th>
                </tr>

                <tr *ngFor="let file of files">
                    <td>
                        <file-row [file]="file"></file-row>
                    </td>
                </tr>
            </tbody>
        </table>
    `,
    providers: [LaputinService]
})
@Injectable()
export class FilesComponent implements OnInit {
    public files: File[] = [];
    private _query: FileQuery = new FileQuery();
    
    constructor(@Inject(LaputinService) private _service: LaputinService) {
    }
    
    ngOnInit(): void {
        this._service.queryFiles(this._query).then((files: File[]) => {
            this.files = files;
        });
    }
    
    filterFiles(query: FileQuery): void {
        this._query = query;
        this._service.queryFiles(query).then((files: File[]) => {
            this.files = files;
        });
    }
    
    openFiles(): void {
        this._service.openFiles(this._query);
    }
}
