// react/js/components/File.js
var _ = require("underscore");
var React = require("react");

var FileTagList = require("./FileTagList");
var TagAutocompletion = require("./TagAutocompletion");
var LaputinAPI = require("./../utils/LaputinAPI");

var File = React.createClass({
    getInitialState: function () {
        return {
            "mode": "read",
            tags: this.props.file.tags,
            newTagName: "",
            showNewTagCreation: false
        }
    },

    addToSelected: function (tag) {
        var self = this;
        LaputinAPI.addTag(this.props.file, tag, function () {
            self.state.tags.push(tag);
            self.setState({ "tags": self.state.tags });
        });
    },

    edit: function () {
        this.setState({ "mode": "edit" });
    },

    cancel: function () {
        this.setState({ "mode": "read" });
    },

    toggle: function () {
        this.setState({ showNewTagCreation: !this.state.showNewTagCreation });
    },

    open: function () {
        LaputinAPI.openFile(this.props.file);
    },

    copy: function () {
        localStorage.setItem("tagClipboard", JSON.stringify(this.state.tags));
    },

    paste: function () {
        var self = this;
        var tags = JSON.parse(localStorage.getItem("tagClipboard"));
        if (tags) {
            _.each(tags, function (tag) {
                self.addToSelected(tag);
            });
        }
    },

    remove: function (tag) {
        var self = this;
        LaputinAPI.deleteTagFileAssoc(this.props.file, tag, function () {
            self.setState({ "tags": _.without(self.state.tags, tag) });
        });
    },

    handleNewTagNameChange: function (e) {
        this.setState({ "newTagName": e.target.value });
    },

    onKeyDown: function (e) {
        var self = this;
        if (e.keyCode === 13 || e.keyCode === 14) {
            LaputinAPI.createTag(this.state.newTagName, function (tag) {
                self.setState({ "newTagName": "" });
                self.addToSelected(tag);
            });
        }
    },

    render: function() {
        var tagCreation = "";
        if (this.state.showNewTagCreation) {
            tagCreation = <form>
                <input type="text" value={this.state.newTagName} onChange={this.handleNewTagNameChange} onKeyDown={this.onKeyDown}
                       placeholder="Create a new tag" className="form-control" />
            </form>;
        }

        if (this.state.mode === "edit") {
            var remove = this.remove;
            var tags = _.sortBy(this.state.tags, function (tag) { return tag.name });

            return <div>
                <p><a onClick={this.cancel}><strong>{this.props.file.name}</strong></a></p>
                <div className="row">
                    <div className="col-md-2">
                        <TagAutocompletion callback={this.addToSelected} selectedTags={this.state.tags} unassociated="1" />

                        <p>
                            <small><a onClick={this.toggle}>Didn't find the tag you were looking for..?</a></small>
                        </p>

                        {tagCreation}

                        <p><small><a onClick={this.copy}>Copy</a> <a onClick={this.paste}>Paste</a></small></p>
                        <p><small><a onClick={this.open}>Open only this file</a></small></p>
                    </div>
                    <div className="col-md-10">
                        {tags.map(function (tag) {
                            var hack = function () { remove(tag) };
                            return <button onClick={hack} className="btn btn-success tag">{tag.name}</button>;
                        })}
                    </div>
                </div>
            </div>
        }

        return <div>
            <a onClick={this.edit}>{this.props.file.name}</a>
            <FileTagList tags={this.state.tags} />
        </div>;
    }
});



module.exports = File;

// src/client/app/components/file.component.ts
import {Component, Input, EventEmitter, Injectable, Inject} from "@angular/core";
import * as _ from "lodash";

import {LaputinService} from "./../services/laputinservice";
import {File} from "./../models/file";
import {FileQuery} from "./../models/filequery";
import {Tag} from "./../models/tag";

@Component({
    selector: "file-row",
    template: `
        <div>
            <div *ngIf="!detailsOpen">
                <p><a (click)="toggle()">{{file.path}}</a></p>
                
                <p>{{formattedTags()}}</p>
            </div>

            <div *ngIf="detailsOpen">
                <p><strong><a (click)="toggle()">{{file.path}}</a></strong></p>
            
                <div class="row">
                    <div class="col-md-2">
                        <p>
                            <tag-autocomplete [tagContainer]="file" (select)="addTag($event)"></tag-autocomplete>
                        </p>
                        
                        <p>
                            <small><a (click)="toggleTagCreation()">Didn't find the tag you were looking for..?</a></small>
                        </p>
                        
                        <div *ngIf="tagCreationOpen">
                            <search-box (update)="addNewTag($event)" clearOnEnter="1"></search-box>
                        </div>

                        <p><small><a (click)="copy()">Copy</a> <a (click)="paste()">Paste</a></small></p>
                        <p><small><a (click)="openFile()">Open</a></small></p>
                    </div>
                    
                    <div class="col-md-10">
                        <p>
                            <span *ngFor="let tag of file.tags">
                                <button (click)="removeTag(tag)" class="btn btn-success tag">{{tag.name}}</button>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        </div>`,
    providers: [LaputinService]
})
@Injectable()
export class FileRowComponent {
    @Input() file: File;
    
    public detailsOpen: boolean = false;
    public tagCreationOpen: boolean = false;
    
    constructor(@Inject(LaputinService) private _service: LaputinService) {
    }
    
    public toggle(): void {
        this.detailsOpen = !this.detailsOpen;
    }
    
    public toggleTagCreation(): void {
        this.tagCreationOpen = !this.tagCreationOpen;
    }
    
    public addNewTag(newTag: string): void {
        this._service.createTag(this.file, newTag)
                     .subscribe(tag => {
                        this._service.addTag(this.file, tag)
                            .subscribe(() => this.addTagsToFile([tag]));
                     });
    }
    
    public addTag(tag: Tag): void {
        this.addTags([tag]);
    }
    
    public addTags(tags: Tag[]): void {
        this._service.addTags(this.file, tags)
                     .subscribe(() => this.addTagsToFile(tags));
    }
    
    public removeTag(tag: Tag): void {
        var tags = this.file.tags;
        this.file.tags = _.filter(this.file.tags, (t: Tag): boolean => t.id !== tag.id);
        this._service.deleteTagFileAssoc(this.file, tag)
            .subscribe(() => {});
    }
    
    private addTagsToFile(tags: Tag[]): void {
        var currentTags = this.file.tags;
        _.each(tags, (tag: Tag) => currentTags.push(tag));
        var sorted = _.sortBy(currentTags, (tag: Tag) => tag.name);
        this.file.tags = sorted;
    }
    
    public openFile(): void {
        var query = new FileQuery();
        query.hash = this.file.hash;
        
        this._service.openFiles(query);
    }
    
    public copy(): void {
        localStorage.setItem("tagClipboard", JSON.stringify(this.file.tags));
    }

    public paste(): void {
        var tags = JSON.parse(localStorage.getItem("tagClipboard"));
        this.addTags(tags);
    }
    
    public formattedTags(): string {
        return _.map(this.file.tags, (tag) => tag.name).join(", ");
    }
}
